language: ruby

before_script: rails g rspec:install

script: bundle exec rspec spec

rvm:
  - 2.2.0 
notifications:
  email:
    recipients:
      - johnnys.ribeiro@gmail.com
      - icyrvnd@gmail.com
      - simiaosimis@gmail.com
      - tmb0710@gmail.com
branches:
  only:
  
  - dev
